### PR TITLE
Fix summary page time not calculated correctly

### LINKED ISSUE #600: Wrong editor time displayed in all time summary
**Describe the bug**
The editor time displayed on the main page of the summary (in my case for Android Studio) is oddly low. If you click on a project that mainly used this editor, the time is higher than on the main page. This is strange as it should contain all the data from the subprojects.

**System information**
* Wakapi version `2.10.4`
* Operating system
    * If Linux: which distro? `Ubuntu 22.04.3 LTS`
    * If Docker: which image and tag? `ghcr.io/muety/wakapi:2.10.4`
* Database `Postgres`

Global Editor chart (All Time):
grafik

Editor Chart of a project (All Time)
Bildschirmfoto vom 2024-01-30 17-51-12

### PR DESCRIPTION
**Pull request by ddadaal**
Fix #600.

See https://github.com/muety/wakapi/issues/600#issuecomment-1921723789

After applying the fix, run Regenerate Summaries from /settings#danger_zone.

### CODE REVIEW

**Comment by ddadaal** [comment]
@muety This PR fixes #600. Please have it reviewed if it's convenience to you.

File: repositories/summary.go [hunk 1]
```diff
@@ -36,28 +36,42 @@ func (r *SummaryRepository) GetAll() ([]*models.Summary, error) {
 
 func (r *SummaryRepository) Insert(summary *models.Summary) error {
 
-	itemsToCreate := []interface{}{summary}
+	if err := r.db.Transaction(func(tx *gorm.DB) error {
+		if err := r.db.Create(summary).Error; err != nil {
```
Comment (muety) [inline repositories/summary.go:40]: Doesn't seem to be working for me, sorry. When letting the `AggregationService` create summaries on startup, it would get stuck while trying to persist the very first summary in list. Precisely, it seems to get stuck it this very line, that is, the `Create()` would never return. Probably has got to do with the transaction management. I'm using MySQL. 

These are the logs:

```
2024-02-02T14:58:00.019589431+01:00 [INFO ] generating summaries
2024/02/02 14:58:00 /home/ferdinand/go/src/github.com/muety/wakapi/repositories/summary.go:114
[55.661ms] [rows:270] SELECT users.id as `user`, max(to_time) as time FROM `users` left join summaries on users.id = summaries.user_id GROUP BY `users`.`id`
2024/02/02 14:58:07 /home/ferdinand/go/src/github.com/muety/wakapi/repositories/heartbeat.go:140
[7594.383ms] [rows:270] SELECT users.id as `user`, min(time) as `time` FROM `users` left join heartbeats on users.id = heartbeats.user_id GROUP BY `users`.`id`
2024/02/02 14:58:10 /home/ferdinand/go/src/github.com/muety/wakapi/repositories/heartbeat.go:97
[48.463ms] [rows:0] SELECT * FROM `heartbeats` WHERE `heartbeats`.`user_id` = 'n1try' AND time >= '2021-02-11 00:00:00' AND time < '2021-02-12 00:00:00' ORDER BY time asc
2024/02/02 14:58:10 /home/ferdinand/go/src/github.com/muety/wakapi/repositories/language_mapping.go:42
[0.726ms] [rows:2] SELECT * FROM `language_mappings` WHERE `language_mappings`.`user_id` = 'n1try'
2024-02-02T14:58:10.921284153+01:00 [INFO ] successfully generated summary (2021-02-11 00:00:00 +0100 CET, 2021-02-12 00:00:00 +0100 CET, n1try)
```

Sorry for the struggle! Let me know if you want me to try to take over.

Comment (ddadaal) [reply repositories/summary.go]: Sorry my bad. I should use `tx` instead of the original `r.db` to create the entities. I rewrote the code because the master has changed since the original fix, and just missed the part. I just pushed a new commit to resolve this, please check the latest one.

**Comment by muety** [comment]
Thank you!
