### PR TITLE
fix: drop_badges_column migration for sqlite

### LINKED ISSUE #128: [ERROR] migration '20210206_drop_badges_column_add_sharing_flags' failed
```
2021-02-16T02:33:58.628088167Z [INFO ] potentially running migration '20210206_drop_badges_column_add_sharing_flags'
2021-02-16T02:33:58.701952316Z [ERROR] migration '20210206_drop_badges_column_add_sharing_flags' failed – table users already exists
panic: migration '20210206_drop_badges_column_add_sharing_flags' failed – table users already exists

goroutine 1 [running]:
github.com/emvi/logbuch.(*StandardFormatter).Pnc(0xc00000e060, 0xcf51c2, 0x1c, 0xc00117d940, 0x2, 0x2)
	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/standard_formatter.go:59 +0x8e
github.com/emvi/logbuch.(*Logger).Fatal(0xc00010c000, 0xcf51c2, 0x1c, 0xc00117d940, 0x2, 0x2)
	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/logger.go:132 +0xb3
github.com/emvi/logbuch.Fatal(...)
	/go/pkg/mod/github.com/emvi/logbuch@v1.1.1/funcs.go:55
github.com/muety/wakapi/migrations.RunCustomPostMigrations(0xc0010d84b0, 0xc00012c9a0)
	/src/migrations/migrations.go:52 +0x24a
main.main()
	/src/main.go:122 +0x3aa
0
```

```
sqlite> .schema users
CREATE TABLE users
(
    id       varchar(255) primary key,
    api_key  varchar(255) unique,
    password varchar(255)
, `created_at` timestamp default '2020-01-01T00:00:00.000' not null, `last_logged_in_at` timestamp default '2020-01-01T00:00:00.000' not null, `badges_enabled` tinyint(1) default 0 not null, `wakatime_api_key` text, `share_oss` numeric DEFAULT false, `has_data` numeric DEFAULT false, `is_admin` numeric DEFAULT false, `share_data_max_days` integer DEFAULT 0, `share_languages` numeric DEFAULT false, `share_editors` numeric DEFAULT false, `share_projects` numeric DEFAULT false, `share_machines` numeric DEFAULT false);
```

Version: latest/1.24.1 on Docker Hub

### PR DESCRIPTION
**Pull request by YC**
Avoid DropColumn on Sqlite
Resolves #128

### CODE REVIEW

File: migrations/20210206_drop_badges_column_add_sharing_flags.go [hunk 1]
```diff
@@ -37,6 +37,12 @@ func init() {
 				return err
 			}
 
+			if cfg.Db.Dialect == config.SQLDialectSqlite {
+				// see 20201106_migration_cascade_constraints
+				logbuch.Info("not attempting to drop and regenerate constraints on sqlite")
```
Comment (muety) [inline migrations/20210206_drop_badges_column_add_sharing_flags.go:42]: Thanks for the contribution! Please adapt the error message to this specific migration as it's not quite accurate here. Afterwards I'm going to merge this.
